
# crypto based as unique identifiers 
identifiers: 
  # crypto for the task (same for all robots/services on the same task)
  task: test_cert 

addresses:
  signaling_server_address: '127.0.0.1:8000'
  
topics:
  - topic_name: /dvrk/PSM2/set_joints_and_jaw
    topic_type: std_msgs/msg/Float64MultiArray
    qos: fast
  - topic_name: /dvrk/PSM2/state_jaw_current 
    topic_type: sensor_msgs/msg/JointState
    qos: fast
  - topic_name: /dvrk/PSM2/state_joint_current
    topic_type: sensor_msgs/msg/JointState
    qos: fast
  - topic_name: /img_zivid
    topic_type: sensor_msgs/msg/CompressedImage
    qos: fast

# declare possible states 
# pub: publish to the swarm
# sub: subscribe to the swarm
# note this is reversed from prior version of SGC config file
state_machine: 
  talker: 
    topics:
      # - /chatter: pub 
      - /dvrk/PSM2/set_joints_and_jaw: sub 
      - /dvrk/PSM2/state_jaw_current: pub 
      - /dvrk/PSM2/state_joint_current: pub 
      - /img_zivid: pub 
  listener: 
    topics:
      # - /chatter: sub 
      - /dvrk/PSM2/set_joints_and_jaw: pub 
      - /dvrk/PSM2/state_jaw_current: sub 
      - /dvrk/PSM2/state_joint_current: sub 
      - /img_zivid: sub 

# name: state
# name need to match the identitifer's whoami
# state should be declared in possible states 
# Phase 1: only allow changing the assignment at runtime 
assignment:
  machine_talker: talker
  machine_listener: listener

topology:
  machine_talker:
    children: 
      - machine_listener

# bindings:
#   enp5s0: 128.32.37.36
#   wlo1: "54.176.160.12"