identifiers: 
  task: test_cert 

topics:
  - topic_name: /parking_stream_0/compressed
    topic_type: sensor_msgs/msg/CompressedImage
    qos: fast 
  - topic_name: /parking_stream_1/compressed
    topic_type: sensor_msgs/msg/CompressedImage
    qos: fast 
  - topic_name: /parking_stream_2/compressed
    topic_type: sensor_msgs/msg/CompressedImage
    qos: fast 
  - topic_name: /parking_stream_3/compressed
    topic_type: sensor_msgs/msg/CompressedImage
    qos: fast 
  - topic_name: /latency_feedback/compressed
    topic_type: sensor_msgs/msg/CompressedImage
    qos: fast 

state_machine:
  talker:
    topics:
      - /parking_stream_0/compressed: pub
      - /parking_stream_1/compressed: pub
      - /parking_stream_2/compressed: pub
      - /parking_stream_3/compressed: pub
      - /latency_feedback/compressed: sub
  listener:
    topics:
      - /parking_stream_0/compressed: sub
      - /parking_stream_1/compressed: sub
      - /parking_stream_2/compressed: sub
      - /parking_stream_3/compressed: sub
      - /latency_feedback/compressed: pub
assignment:
  machine_talker: talker
  machine_listener: listener

topology:
  machine_talker:
    children: 
      - machine_listener