identifiers: 
  task: test_cert 

services:
  - service_name: /sam
    service_type: shared_srvs/srv/Sam

state_machine: 
  standby: 
  client: 
    services:
      - /sam: client 
  server: 
    services:
      - /sam: service 




# EXAMPLE #1: 2 servers and 1 client
assignment:
  machine_client: client
  machine_server_1: server
  machine_server_2: server

topology:
  machine_client:
    children: 
      - machine_server_1
      - machine_server_2


# EXAMPLE #2: server -> switch -> client 
# assignment: 
#   machine_client: client
#   machine_server: server
#   machine_switch: standby

# topology:
#   machine_client:
#     children: 
#       - machine_switch:
#           children: 
#             - machine_server