identifiers: 
  task: test_cert 

addresses:
  signaling_server_address: '3.18.194.127:8000'

services:
  - service_name: /yolo
    service_type: shared_srvs/srv/Yolo

state_machine: 
  standby: 
  client: 
    services:
      - /yolo: client 
  server: 
    services:
      - /yolo: service 
      
assignment:
  machine_client: client
  machine_server: server

topology:
  machine_client:
    children: 
      - machine_server
