identifiers: 
  task: test_cert 

topics:
  - topic_name: /chatter
    topic_type: std_msgs/msg/String

services:
  - service_name: /add_three_ints
    service_type: bench_msgs/srv/AddThreeInts

state_machine: 
  standby: 
  client: 
    topics: 
      - /chatter: pub 
    services:
      - /add_three_ints: client 
  server: 
    topics: 
      - /chatter: sub
    services:
      - /add_three_ints: service 

assignment:
  machine_client: client
  machine_server: server
  machine_switch: standby