
# crypto based as unique identifiers 
identifiers: 
  # crypto for the task (same for all robots/services on the same task)
  task: test_cert 

addresses:
  signaling_server_address: '20.172.64.185:8000'

topics:
  - topic_name: /chatter
    topic_type: std_msgs/msg/String
    qos: fast 

# declare possible states 
# pub: publish to the swarm
# sub: subscribe to the swarm
# note this is reversed from prior version of SGC config file
state_machine: 
  talker: 
    topics:
      - /chatter: pub 
  listener: 
    topics:
      - /chatter: sub 

# name: state
# name need to match the identitifer's whoami
# state should be declared in possible states 
# Phase 1: only allow changing the assignment at runtime 
assignment:
  machine_talker: talker
  machine_listener: listener

topology:
  machine_talker:
    children: 
      - machine_listener

# bindings:
#   enp5s0: 128.32.37.36
#   wlo1: "54.176.160.12"