[clog]
repository = "https://github.com/data-capsule/gdp-router"
outfile = "CHANGELOG.md"
from-latest-tag = true

[sections]
Performance = ["perf"]
Improvements = ["impr", "im", "imp"]
Documentation = ["docs"]
Deprecations = ["depr"]
Examples = ["examples"]
"API Additions" = ["add", "api"]
Meta = ["meta"]
